%AUTHOR - Justin
%Designed to find the peaks in the result generated by the f_mvpwr_acp
%function. Returns arrau of peaks and their relative times.
%Takes: [[mvpwacf values], [sampling frequency]]
%returns: [[peaks], [peak rel. times]]

function [peak_values, peak_times] = f_peak_finder_acfwind(acp_window, sampling_f)
%debug flag
debug = 0;

%META PARAMETERS
max_bpm = 200;
min_peak_prom = 15;

minPeakDistance=60/max_bpm;

%Find the peaks and locations
[peak_values,peak_times] = findpeaks(acp_window,sampling_f,'MinPeakDistance',minPeakDistance,...
    'MinPeakProminence',min_peak_prom);

%Last peak MUST be max value (For some reason, the findpeaks doesn't know this)
[mv, mi] = max(acpshort)
if(~isempty(peak_values))
    peak_values(length(peak_values)) = mv;
    peak_times(length(peak_times)) = mi/fs;
end

%Remove 'bad' peaks (If you correlate less than a previous 'peak' you are unlikely a beat...)
i = 2;
while(i < length(peak_values)+1)
    if(peak_values(i-1) > peak_values(i))
        peak_values(i) = [];
        peak_times(i) = [];
    else
    i = i + 1;
    end
end

%Plot the corrected peak markers
if(debug)
    figure();
    plot(acpshort)
    hold on;
    plot(peak_times*fs, peak_values, 'x');
    hold off;
    title("Plot of autocorrelated moving average power")
    xlabel('Time Instance (s)')
end


end